---
title: "Soil Extracts CDOM Analysis"
output: html_document
date: "2022-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages and Data

```{r, message=FALSE, echo =FALSE, warning = FALSE}
# required packages
packages_list <- c("tidyverse", "broom", "ggpubr", "ggfortify", "GGally",
                   "rstatix")

lapply(packages_list, library, character.only = TRUE)

# set data files location
cdom_data_location = paste0(getwd(), "/Original Data Files")

# csv files for CDOM data
water_cdom_peaks <- read_csv(paste0(cdom_data_location, "/EC1_Water_CDOM_DOCnormalizedpeakpicks_20221011.csv"))
water_cdom_indices <- read_csv(paste0(cdom_data_location, "/EC1_Water_CDOM_SpectralIndices_20221011.csv"))

extracts_cdom_peaks <- read_csv(paste0(cdom_data_location,
                                       "/EC1_WSOC_Extracts_Nov2022_PeakPicks_DOCnormalized.csv"))
extracts_cdom_indices <- read_csv(paste0(cdom_data_location, "/EC1_WSOC_Extracts_Nov2022_SpectralIndices.csv"))
```

## Set-Up

```{r}
# set ggplot theme - remove dark background
theme_set(theme_bw() +
             theme(text = element_text(family = "serif"),
                  axis.title = element_text(size = 20),
                  axis.text = element_text(size = 18),
                  legend.text = element_text(size = 18),
                  legend.title = element_text(size = 20)))

# create color palette
palette <- c("#056009","#0385B5","#021677","#ABABD9","#27220F","#8E7941",
             "#DCCD6A","#8F8D90")

# set location for saved figures
output_directory <- "./Saved Figures"
```

## Aqualog Abs Data Figure

```{r}
abs_path <- "C:/Users/mcel487/OneDrive - PNNL/Documents/SULI Project 2022/CDOM Data/EC1_WSOC_Extracts_CDOM_processed/5. Corrected Absorbance Files_ESS_DIVE/K035 UP_DilCorr_Abs.dat"

# precheck to look at data format
readLines(abs_path, n = 10)

abs_spectra <- read.delim(abs_path, header = TRUE, sep = "\t")

# plot
ggplot(abs_spectra, aes(x = Wavelength..nm., y = Dilution.Corrected.Absorbance)) +
  geom_line() +
  labs(x = "Wavelength (nm)", y = "Absorbance") +
  scale_x_continuous(breaks = seq(200, 800, by = 100))

ggsave("abs_spectra.png", path = output_directory,
       width = 7, height = 5)
```

## Data Preparation

```{r}
# data frame edits
extracts_cdom_indices <- extracts_cdom_indices %>%
  filter(!is.na(SUVA254))

names(extracts_cdom_peaks) <- gsub(pattern = "_per_unitDOC", replacement = "", 
                                   x =names(extracts_cdom_peaks))

names(water_cdom_peaks) <- gsub(pattern = "_per_unitDOC", replacement = "",
                                x = names(water_cdom_peaks))

colnames(extracts_cdom_indices)[1] <- "kit_id"
colnames(extracts_cdom_peaks)[1] <- "kit_id"
colnames(water_cdom_indices)[1] <- "kit_id"
colnames(water_cdom_peaks)[1] <- "kit_id"

# merge peaks and indices together
extracts_cdom_original <- left_join(extracts_cdom_indices, extracts_cdom_peaks, by = "kit_id")
water_cdom <- left_join(water_cdom_indices, water_cdom_peaks, by = "kit_id")

# add a transect_location column
water_cdom <- water_cdom %>%
  mutate(transect_location = "Water")
water_cdom <- water_cdom[,c(1,2,27,3:26)]

extracts_cdom_original <- extracts_cdom_original %>%
  mutate(transect_location = case_when(
    grepl("T", kit_id) ~ "Transition",
    grepl("UP", kit_id) ~ "Upland",
    grepl("W", kit_id) ~ "Wetland"
  ))
extracts_cdom_original <- extracts_cdom_original[,c(1,2,27,3:26)]
```

```{r}
## work with kit replicates
# change kit id names
extracts_cdom_original <- extracts_cdom_original %>%
  mutate(kit_id = substr(kit_id, 1,4))
extracts_cdom_original <- extracts_cdom_original %>%  
  mutate(kit_id = case_when(
    grepl("(Rep)", extracts_cdom_original$Sample_Description) ~ paste0(kit_id,"_rep"),
    !grepl("(Rep)", extracts_cdom_original$Sample_Description) ~ kit_id))

# pull out replicate kits and matches for potential error calculation
extracts_cdom_rep_list <- extracts_cdom_original %>%
  filter(grepl("_rep", kit_id))
extracts_cdom_reps <- extracts_cdom_original %>%
  filter(substr(extracts_cdom_original$Sample_Description,1,9) %in% 
           substr(extracts_cdom_rep_list$Sample_Description,1,9))

## calculate averages
# make dataset copy
extracts_cdom_reps_sum <- extracts_cdom_reps

# replace kit names to be able to group by kit easier
extracts_cdom_reps_sum$kit_id[grepl("_rep", extracts_cdom_reps_sum$kit_id)] <- gsub(pattern = "_rep",
                                                                                    replacement = "", 
                                                                                    x = extracts_cdom_reps_sum$kit_id[grepl("_rep", extracts_cdom_reps_sum$kit_id)])

# remove unneeded columns
extracts_cdom_reps_sum <- extracts_cdom_reps_sum[,-2]

# group by kit_id and location and calculate averages of the metrics
extracts_cdom_reps_sum <- extracts_cdom_reps_sum %>%
  group_by(kit_id, transect_location) %>%
  summarize(across(everything(), mean))

## replace replicate kit values with averages
# remove replicate labelled rows
extracts_cdom_original <- extracts_cdom_original %>%
  filter(!grepl("_rep", kit_id)) %>%
  select(-Sample_Description)

# use rows_update() function
extracts_cdom <- extracts_cdom_original %>%
  rows_update(extracts_cdom_reps_sum, by = c("kit_id", "transect_location"))
```

```{r}
## merge CDOM datasets together 
water_cdom <- water_cdom[,-2]
extract_sites_CDOM <- rbind(extracts_cdom, filter(water_cdom, water_cdom$kit_id %in% extracts_cdom$kit_id))

```

```{r}
# bring in metadata to get location information for the kits
water_soil <- read_rds("./R Data Files/EC1_water_soil_data.rds")

# change region name for Chesapeake to Mid-Atlantic (for figures)
water_soil <- water_soil %>%
  mutate(region = ifelse(region == "Chesapeake Bay", "Mid-Atlantic", "Great Lakes"))
water_soil$region <- as.factor(water_soil$region)

# merge info with cdom data
water_soil_location <- water_soil %>%
  select(kit_id, state, region, water_body, water_systemtype)

extract_sites_CDOM <- left_join(extract_sites_CDOM, water_soil_location, by = "kit_id")
extract_sites_CDOM <- unique(extract_sites_CDOM)

# relevel transect_location
extract_sites_CDOM$kit_id <- as.factor(extract_sites_CDOM$kit_id)
extract_sites_CDOM$transect_location <- factor(extract_sites_CDOM$transect_location,
                                               levels = c("Upland", "Transition", "Wetland", "Water"))
```

## Preliminary PCA

```{r}
# set up data frame
pca_extracts_cdom <- extract_sites_CDOM[,c(3,4,6,8:13)]

# pull kit IDs to change the row names for labels on the PCA plot
extracts_kit_id <- extract_sites_CDOM[,1]

# change row names of data frame used for PCA
# row.names(pca_extracts_cdom) <- pca_extracts_cdom
# error message 

# calculate the principal components
pc <- prcomp(pca_extracts_cdom, scale = TRUE)

# reverse signs of eigenvectors
pc$rotation <- -1*pc$rotation

# look at the principal components
pc$rotation

# reverse signs of each observation's principal components scores
pc$x <- -1*pc$x

# calculate variance represented by each of the principal components
pc$sdev^2 / sum(pc$sdev^2)
```

```{r}
## preliminary PCA plots
# visualize the PCA
biplot(pc, scale = 0)

# add data about transect location
pca_plot <- autoplot(pc, data = extract_sites_CDOM, colour = 'transect_location', frame = T, size = 3, loadings = TRUE,
         loadings.colour = 'black', loadings.label = TRUE,
         loadings.label.colour = 'black')
pca_plot
pca_plot + scale_fill_manual(values = palette) + 
  scale_color_manual(values= palette) +
  labs(color = "Gradient Location", fill = "Gradient Location")

# try kit id
autoplot(pc, data = extract_sites_CDOM, colour = 'kit_id', size = 3, loadings = TRUE,
         loadings.colour = 'black', loadings.label = TRUE)
# no cluster pattern here

# try region and transect location
autoplot(pc, data = extract_sites_CDOM, size = 3, frame = T,
         shape = 'region', loadings.colour = "black", loadings.label = TRUE)
```

## Rerun PCA with only FRESH to reduce loadings

```{r}
# calculate the principal components
pc2 <- prcomp(pca_extracts_cdom[,c(1,3,6:8)], scale = TRUE)

# reverse signs of eigenvectors
pc2$rotation <- -1*pc2$rotation

# reverse signs of each observation's principal components scores
pc2$x <- -1*pc2$x

# calculate variance represented by each of the principal components
pc2$sdev^2 / sum(pc2$sdev^2)
```

```{r}
# plot the new PCA
new_pca_plot <- autoplot(pc2, data = extract_sites_CDOM, colour = 'transect_location',
                         shape = 'region',
                         frame = T, size = 3, loadings = TRUE,
         loadings.colour = 'black', loadings.size = 3, loadings.label = TRUE,
         loadings.label.colour = 'black',
         loadings.label.hjust = 1.1, loadings.label.vjust = 1.5,
         loadings.label.size = 5.5)

new_pca_plot + scale_fill_manual(values = palette) + 
  scale_color_manual(values= palette) +
  labs(color = "Gradient Location", fill = "Gradient Location", shape = "Region")

ggsave("cdom_pca.png", path = output_directory,
       width = 9, height = 5)

```

```{r}
# work more with ggplot and clustering analysis
## customize plots with ggplot
# pull out needed info
pc_df <- data.frame(pc$x, transect_location = extract_sites_CDOM$transect_location,
                    region = extract_sites_CDOM$region)

# ggplot
ggplot(pc_df, aes(x = PC1, y = PC2, color = transect_location, shape = region)) +
  geom_point(size = 2.5) +
  scale_color_manual(values = palette)

# set up for clustering 
# https://stackoverflow.com/questions/20260434/test-significance-of-clusters-on-a-pca-plot
scores <- pc2$x[,1:3]                        # scores for first three PC's

# k-means clustering
km     <- kmeans(scores, centers=4, nstart=5)
ggdata <- data.frame(scores, Cluster=km$cluster, location=extract_sites_CDOM$transect_location,
                     region = extract_sites_CDOM$region)

ggplot(ggdata) +
  geom_point(aes(x=PC1, y=PC2, color=factor(location),shape=factor(region)), size=2.5) +
  stat_ellipse(aes(x=PC1,y=PC2,fill=factor(Cluster)),
               geom="polygon", level=0.95, alpha=0.2) +
  guides(color=guide_legend("location"),fill=guide_legend("Cluster"))

```

## Correlations between CDOM Spectral Metrics

```{r, message = FALSE, warning = FALSE}
cdom_corr <- pca_extracts_cdom
cdom_groups <- as.data.frame(extract_sites_CDOM[,2])

# correlation scatter plot
ggpairs(cdom_corr, ggplot2::aes(color = cdom_groups$transect_location),
        #lower = list(continuous = "smooth"), # adds lm line to the scatterplots
        columnLabels = c("SUVA 254 nm", "Spectral Slope 275-295 nm", "Spectral Slope 350-400 nm",
                         "Slope Ratio", "E2 to E3", "FI", "HIX", "FRESH", "BIX")) +
  ggplot2::scale_fill_manual(values = palette) +
  ggplot2::scale_color_manual(values = palette)
```

## Pulling Specific Metrics

```{r}
# two absorbance metrics
ggplot(extract_sites_CDOM, aes(x = SUVA254, y = S350_400, color = transect_location)) +
  geom_point(size = 2.5) +
  scale_color_manual(values = palette) +
  labs(x = "SUVA at 254 nm", y = "Spectral Slope 350-400 nm", color = "Gradient Location")

ggsave("SUVA254_S350_400.png", path = output_directory,
       height = 5, width = 7)
```

```{r}
# two fluorescence metrics
ggplot(extract_sites_CDOM, aes(x = FI, y = FRESH, color = transect_location)) +
  geom_point(size = 2.5) +
  scale_color_manual(values = palette) +
  labs(x = "Fluorescense Index", y = "Freshness Index", color = "Gradient Location")

ggsave("FI_FRESH.png", path = output_directory,
       height = 5, width = 7)
```

### Summary Stats for FRESH, FI, HIX, SUVA254, and S350_400

```{r}
CDOM_sum_mean <- extract_sites_CDOM %>%
  select(transect_location, SUVA254, S350_400, FI, FRESH, HIX) %>%
  group_by(transect_location) %>%
  summarize(across(everything(), mean))

colnames(CDOM_sum_mean)[-1] <- paste0(colnames(CDOM_sum_mean)[-1], "_mean")

CDOM_sum_sd <- extract_sites_CDOM %>%
  select(transect_location, SUVA254, S350_400, FI, FRESH, HIX) %>%
  group_by(transect_location) %>%
  summarize(across(everything(), sd))

# calculate standard error
CDOM_sum_se <- CDOM_sum_sd
CDOM_sum_se[,c(2:6)] <- CDOM_sum_se[,c(2:6)]/sqrt(10)   # each transect location has 10 samples

colnames(CDOM_sum_se)[-1] <- paste0(colnames(CDOM_sum_se)[-1], "_se")
```

```{r}
# boxplots for indices across the gradient
SUVA <- ggplot(extract_sites_CDOM, aes(x = transect_location, y = SUVA254, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "SUVA at 254 nm (L/mg C*m)", color = "") +
  theme(axis.title.x = element_blank(),     
        axis.text.x = element_blank())    # remove the axis labels and ticks for common axis in ggarrange()

SS <- ggplot(extract_sites_CDOM, aes(x = transect_location, y = S350_400, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Spectral Slope (350-400 nm)", color = "") +
  theme(axis.title.x = element_blank(),     
        axis.text.x = element_blank())

FI <- ggplot(extract_sites_CDOM, aes(x = transect_location, y = FI, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Fluorescence Index", color = "")

FRESH <- ggplot(extract_sites_CDOM, aes(x = transect_location, y = FRESH, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Freshness Index", color = "")

HIX <- ggplot(extract_sites_CDOM, aes(x = transect_location, y = HIX, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Humification Index", color = "")

# pull all plots into one figure
ggarrange(SUVA, SS, FI, FRESH, HIX,
          labels ="AUTO", align = "hv")

ggsave("cdom_indices_boxplots.png", path = output_directory,
       width = 16, height = 9)
```

```{r}
#checking normality for ANOVA
ggplot(extract_sites_CDOM, aes(x = SUVA254, color = transect_location)) +
  geom_density()
ggplot(extract_sites_CDOM, aes(x = S350_400, color = transect_location)) +
  geom_density()
ggplot(extract_sites_CDOM, aes(x = FRESH, color = transect_location)) +
  geom_density()
ggplot(extract_sites_CDOM, aes(x = FI, color = transect_location)) +
  geom_density()
ggplot(extract_sites_CDOM, aes(x = HIX, color = transect_location)) +
  geom_density()

# no way to transform well either - tried ln() and log10() transformation with no success
# proceeded with kruskal-wallis test
```

```{r}
# kruskal-wallis tests for difference between transects for the indices
# SUVA254
kruskal.test(SUVA254 ~ transect_location, extract_sites_CDOM)
dunn_test(extract_sites_CDOM, SUVA254 ~ transect_location, p.adjust.method = "holm")

# S350-400
kruskal.test(S350_400 ~ transect_location, extract_sites_CDOM)
dunn_test(extract_sites_CDOM, S350_400 ~ transect_location, p.adjust.method = "holm")

# FRESH
kruskal.test(FRESH ~ transect_location, extract_sites_CDOM)
dunn_test(extract_sites_CDOM, FRESH ~ transect_location, p.adjust.method = "holm")

# FI
kruskal.test(FI ~ transect_location, extract_sites_CDOM)
dunn_test(extract_sites_CDOM, FI ~ transect_location, p.adjust.method = "holm")

# HIX
kruskal.test(HIX ~ transect_location, extract_sites_CDOM)
dunn_test(extract_sites_CDOM, HIX ~ transect_location, p.adjust.method = "holm")
```

