---
title: "EXCHANGE Data Exploration"
output: html_document
date: "2022-10-07"
---

## Set-Up

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(tidyr)
library(broom)
library(ggplot2)
library(dplyr)
library(ggpubr)
```

```{r}
# build RData file for starting files - files imported in from csv downloads
save(sample_collection_metadata, water_NPOC_TDN, site_metadata,water_spectral_indices, file = "EC1_raw_data.RData")

# load(EC1_raw_data.RData) will bring this into the environment!
```

## Data Preparation

```{r}
# simplify data frame to include coordinates and N/C metrics
water_sample_metadata <- sample_collection_metadata[, c(1:3)]
water <- left_join(water_NPOC_TDN, water_sample_metadata, by = "kit_id")
water <- left_join(water, site_metadata, by = "kit_id")
water_map <- water[,c(3,5,6,9,10,14)]

# match up the spectral data with location of sites and DOC
water_CDOM <- left_join(water, water_spectral_indices, by = c("kit_id", "campaign", "transect_location"))

# pull out the kits without CDOM data to remove NAs
water_CDOM_final <- water_CDOM %>%
  filter(!is.na(SUVA254))

# remove additional columns for dataset ready for analysis
water_CDOM_final <- water_CDOM_final[,c(3,5,6,9,10,14,20:30)]

# make a list of the sites missing CDOM data
water_CDOM_missing <- water_CDOM %>%
  filter(is.na(SUVA254))

water_CDOM_missing <- water_CDOM_missing

water_CDOM_missing <- as.data.frame(water_CDOM_missing)
```

## Load In More Packages for Mapping

```{r, message=FALSE, warning=FALSE}
library(sf)
library(ggspatial)
# both of these packages integrate with ggplot for displaying spatial data

library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)
# this package has important information about the US for drawing map boundaries
```

## Making Maps

```{r}
# pull info from rnaturalearth package to get world information
usa <- ne_countries(country = "United States of America", returnclass = "sf", scale = "large")
lakes <- rnaturalearth::ne_download(scale = 10, type = 'lakes', category = 'physical', returnclass = "sf")

# getting error message here to get more detail map attributes - address later!!

# all water sampling locations plotted!
ggplot(data = usa) +
  geom_sf() +
  coord_sf(xlim = c(-95,-75), ylim = c(35,50)) +
  geom_point(data = water, mapping = aes(x = water_longitude, y = water_latitude, label = kit_id)) +
  geom_label(data = water, aes(x = water_longitude, y = water_latitude, label = kit_id))
```

```{r}
# divide dataframe into two by region for easier mapping
water$region <- as.factor(water$region)
CB_water <- water %>%
  filter(region == "Chesapeake Bay")
GL_water <- water %>%
  filter(region == "Great Lakes")

# zoomed in map for Chesapeake Region with NPOC values
ggplot(data = usa) +
  geom_sf() +
  coord_sf(xlim = c(-77.5,-74.5), ylim = c(37.2,40)) +
  geom_point(data = CB_water, mapping = aes(x = water_longitude, y = water_latitude, color = npoc_mgl)) +
  theme_bw() +
  labs(x = "Longitude", y = "Latitude", color = "NPOC (mg/L)")

# zoomed in map for the Great Lakes
ggplot(data = usa) +
  geom_sf() +
  coord_sf(xlim = c(-95,-78), ylim = c(40,48)) +
  geom_point(data = GL_water, mapping = aes(x = water_longitude, y = water_latitude, color = npoc_mgl)) +
  theme_bw() +
  labs(x = "Longitude", y = "Latitude", color = "NPOC (mg/L)")
```

## Looking at Relationships between Different Spectral Indices

```{r}
# SUVA254 vs S350-400
ggplot(water_CDOM_final, aes(x = SUVA254, y = S350_400)) +
  geom_point() +
  theme_bw() +
  stat_cor()
```

```{r}
# S350-400 vs S275-295
ggplot(water_CDOM_final, aes(x = S275_295, y = S350_400)) +
  geom_point() +
  theme_bw() +
  stat_cor()
```

```{r}
# building a correlation plot!
# prepping data frame with just the variables for calculated correlations
water_corr_plot <- water_CDOM_final[,c(2,7,8,10,12:17)]

# load packages for visualization
library(ggcorrplot)

# compute the correlation matrix for NPOC and the calculated spectral indices
water_corr_matrix <- cor(water_corr_plot)

# calculate p-values for correlations
water_corr_pvalue <- cor_pmat(water_corr_plot)

# basic correlation plot with correlation coefficients
ggcorrplot(water_corr_matrix, hc.order = TRUE,
    type = "lower", lab = TRUE)

# make the correlation plot with significance values
ggcorrplot(water_corr_matrix, hc.order = TRUE,
    type = "lower", method = "circle", p.mat = water_corr_pvalue)
```

## Exploratory PCA (look at potentially redundant CDOM metrics)

```{r}
# https://www.statology.org/principal-components-analysis-in-r/
# set up data frame
water_pca <- water_CDOM_final[,c(7,8,10,12:17)]

# pull kit IDs to change the row names for labels on the PCA plot
kit_id <- water_CDOM_final[,1]

# change row names of data frame used for PCA
rownames(water_pca) <- kit_id
```

```{r}
# calculate the principal components
pc <- prcomp(water_pca, scale = TRUE)

# reverse signs of eigenvectors
pc$rotation <- -1*pc$rotation

# look at the principal components
pc$rotation

# reverse signs of each observation's principal components scores
pc$x <- -1*pc$x

# calculate variance represented by each of the principal components
pc$sdev^2 / sum(pc$sdev^2)
```

```{r}
# visualize the PCA
biplot(pc, scale = 0)
```

## Trying an NMDS to Look at Similar Waters

```{r}
# https://jonlefcheck.net/2012/10/24/nmds-tutorial-in-r/
# load necessary packages
library(vegan)

# run the NMDS use the data frame made for the PCA
site_NMDS = metaMDS(water_pca, k =2)

# Shepard plot to look at the stress
stressplot(site_NMDS)

# plot the NMDS
plot(site_NMDS)

# better plot with labels (run all lines together)
ordiplot(site_NMDS, type = "n")
orditorp(site_NMDS, display = "species")
orditorp(site_NMDS, display = "sites", cex = 1.25)
```

## Cluster Analysis (for a better visual)

```{r}
# http://www.sthda.com/english/wiki/beautiful-dendrogram-visualizations-in-r-5-must-known-methods-unsupervised-machine-learning

# compute Euclidean distance between samples
water_dist <- dist(scale(water_pca), method = "euclidean")

# hierarchical clustering based on the distance matrix
water_cluster <- hclust(water_dist, method = "ward.D2")

# load package for dendrogram visualization
library(ggdendro)

# draw the tree!
ggdendrogram(water_cluster)

# another variation of the tree to visualize the clusters directly (run both lines of code together)
plot(water_cluster, hang = -1) # hang = pulls all of the labels to the same location on the tree
rect.hclust(water_cluster, k =6)
```

