---
title: "Soil Extracts CDOM Analysis"
output: html_document
date: "2022-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages and Data

```{r, message=FALSE, echo =FALSE, warning = FALSE}
# required packages
require(pacman)
pacman::p_load(tidyverse,
               broom,
               ggpubr,
               ggfortify,
               GGally)

# load rds file for surface water data
water_cdom <- read_rds("water_data_mergedwithallmeta.rds")

# load csv files for extract spectral data
extracts_cdom_peaks <- read_csv("./WSOM Extracts Data/EC1_WSOC_Extracts_Nov2022_PeakPicks_DOCnormalized.csv")
extracts_cdom_indices <- read_csv("./WSOM Extracts Data/EC1_WSOC_Extracts_Nov2022_SpectralIndices.csv")
```

## Set-Up

```{r}
# set ggplot theme - remove dark background
theme_set(theme_bw() +
             theme(text = element_text(family = "serif"),
                  axis.title = element_text(size = 20),
                  axis.text = element_text(size = 18),
                  legend.text = element_text(size = 18),
                  legend.title = element_text(size = 20)))

# create color palette
palette <- c("#056009","#0385B5","#021677","#ABABD9","#27220F","#8E7941",
             "#DCCD6A","#8F8D90")

# set location for saved figures
output_directory <- "./Saved Figures"
```

## Aqualog Abs Data Figure

```{r}
abs_path <- "C:/Users/mcel487/OneDrive - PNNL/Documents/GitHub/COMPASS-DOE/JuliaSULI/WSOM Extracts Data/K035 UP_DilCorr_Abs.dat"

# precheck to look at data format
readLines(abs_path, n = 10)

abs_spectra <- read.delim(abs_path, header = TRUE, sep = "\t")

# plot
ggplot(abs_spectra, aes(x = Wavelength..nm., y = Dilution.Corrected.Absorbance)) +
  geom_line() +
  labs(x = "Wavelength (nm)", y = "Absorbance") +
  scale_x_continuous(breaks = seq(200, 800, by = 100))

#ggsave("abs_spectra.png", path = output_directory, width = 7, height = 5)
```

## Data Preparation

```{r CDOM data frame edits}
# reduce columns on water data
water_cdom_original <- water_cdom %>%
  select(campaign, kit_id, contains("water"), collection_date:region)

# remove "water_" from all the water info columns
colnames(water_cdom_original)[grepl("water", colnames(water_cdom_original))] <- gsub("water_", "", colnames(water_cdom_original)[grepl("water", colnames(water_cdom_original))])

# remove the CDOM standards
extracts_cdom_indices <- extracts_cdom_indices %>%
  filter(!is.na(SUVA254))

# edit column names of spreadsheets
names(extracts_cdom_peaks) <- gsub(pattern = "_per_unitDOC", replacement = "", 
                                   x =names(extracts_cdom_peaks))

names(water_cdom_original) <- gsub(pattern = "_per_unitDOC", replacement = "",
                                x = names(water_cdom_original))

# make sure all CDOM output spreadsheets match with kit_id column
colnames(extracts_cdom_indices)[1] <- "kit_id"
colnames(extracts_cdom_peaks)[1] <- "kit_id"
colnames(water_cdom_original)[2] <- "kit_id"

# merge peaks and indices together
extracts_cdom_original <- left_join(extracts_cdom_indices, extracts_cdom_peaks, by = "kit_id")

# add a transect_location column
extracts_cdom_original <- extracts_cdom_original %>%
  mutate(transect_location = case_when(
    grepl("T", kit_id) ~ "Transition",
    grepl("UP", kit_id) ~ "Upland",
    grepl("W", kit_id) ~ "Wetland"
  ))
extracts_cdom_original <- extracts_cdom_original[,c(1,2,27,3:26)]
```

```{r}
## work with kit replicates
# change kit id names
extracts_cdom_original <- extracts_cdom_original %>%
  mutate(kit_id = substr(kit_id, 1,4))
extracts_cdom_original <- extracts_cdom_original %>%  
  mutate(kit_id = case_when(
    grepl("(Rep)", extracts_cdom_original$Sample_Description) ~ paste0(kit_id,"_rep"),
    !grepl("(Rep)", extracts_cdom_original$Sample_Description) ~ kit_id))

# pull out replicate kits and matches for potential error calculation
extracts_cdom_rep_list <- extracts_cdom_original %>%
  filter(grepl("_rep", kit_id))
extracts_cdom_reps <- extracts_cdom_original %>%
  filter(substr(extracts_cdom_original$Sample_Description,1,9) %in% 
           substr(extracts_cdom_rep_list$Sample_Description,1,9))

## calculate averages
# make dataset copy
extracts_cdom_reps_sum <- extracts_cdom_reps

# replace kit names to be able to group by kit easier
extracts_cdom_reps_sum$kit_id[grepl("_rep", extracts_cdom_reps_sum$kit_id)] <- gsub(pattern = "_rep",
                                                                                    replacement = "", 
                                                                                    x = extracts_cdom_reps_sum$kit_id[grepl("_rep", extracts_cdom_reps_sum$kit_id)])

# remove unneeded columns
extracts_cdom_reps_sum <- extracts_cdom_reps_sum[,-2]

# group by kit_id and location and calculate averages of the metrics
extracts_cdom_reps_sum <- extracts_cdom_reps_sum %>%
  group_by(kit_id, transect_location) %>%
  summarize(across(everything(), mean))

## replace replicate kit values with averages
# remove replicate labelled rows
extracts_cdom_original <- extracts_cdom_original %>%
  filter(!grepl("_rep", kit_id)) %>%
  select(-Sample_Description)

# use rows_update() function
extracts_cdom <- extracts_cdom_original %>%
  rows_update(extracts_cdom_reps_sum, by = c("kit_id", "transect_location"))
```

```{r}
## prepare big data frame of all CDOM metrics plus soil/water characteristics
# bring in metadata to get location information for the kits
water_soil <- read_rds("EC1_water_soil_data.rds")

# change region name for Chesapeake to Mid-Atlantic (for figures)
water_soil <- water_soil %>%
  mutate(region = ifelse(region == "Chesapeake Bay", "Mid-Atlantic", "Great Lakes"))
water_soil$region <- as.factor(water_soil$region)

# merge soil characteristics with extract CDOM info
extracts_cdom_info <- extracts_cdom %>%
  filter(!is.na(SUVA254)) %>%
  left_join(select(water_soil, campaign:water_body, water_systemtype, transect_location:percent_sand)) %>%
  relocate(campaign:water_systemtype, .before = SUVA254)

# filter water info to just extract kits and bind extracts and water together
cdom_water_extracts <- water_cdom_original %>%
  filter(kit_id %in% extracts_cdom_info$kit_id) %>%
  bind_rows(extracts_cdom_info)

# work with factor variables
cdom_water_extracts$kit_id <- as.factor(cdom_water_extracts$kit_id)
cdom_water_extracts$transect_location <- factor(cdom_water_extracts$transect_location,
                                               levels = c("Upland", "Transition", "Wetland", "Water"))

# make sure regions are the same between extracts and surface water
cdom_water_extracts <- cdom_water_extracts %>%
  mutate(region = case_when(
    region == "Chesapeake Bay" ~ "Mid-Atlantic",
    TRUE ~ region
  ))
```

## Preliminary PCA

```{r}
# set up data frame
pca_extracts_cdom <- cdom_water_extracts %>%
  select(SUVA254, S275_295, S350_400, Sr:BIX)

# pull kit IDs to change the row names for labels on the PCA plot
extracts_kit_id <- cdom_water_extracts[,1]

# change row names of data frame used for PCA
# row.names(pca_extracts_cdom) <- pca_extracts_cdom
# error message 

# calculate the principal components
pc <- prcomp(pca_extracts_cdom, scale = TRUE)

# reverse signs of eigenvectors
pc$rotation <- -1*pc$rotation

# look at the principal components
pc$rotation

# reverse signs of each observation's principal components scores
pc$x <- -1*pc$x

# calculate variance represented by each of the principal components
pc$sdev^2 / sum(pc$sdev^2)
```

```{r}
## preliminary PCA plots
# visualize the PCA
biplot(pc, scale = 0)

# add data about transect location
pca_plot <- autoplot(pc, data = cdom_water_extracts, colour = 'transect_location', frame = T, size = 3, loadings = TRUE,
         loadings.colour = 'black', loadings.label = TRUE,
         loadings.label.colour = 'black')
pca_plot
pca_plot + scale_fill_manual(values = palette) + 
  scale_color_manual(values= palette) +
  labs(color = "Gradient Location", fill = "Gradient Location")

# try kit id
autoplot(pc, data = cdom_water_extracts, colour = 'kit_id', size = 3, loadings = TRUE,
         loadings.colour = 'black', loadings.label = TRUE)
# no cluster pattern here

# try region and transect location
autoplot(pc, data = cdom_water_extracts, size = 3, frame = T,
         shape = 'region', loadings.colour = "black", loadings.label = TRUE)
```

## Rerun PCA with only FRESH to reduce loadings

```{r}
# calculate the principal components
pc2 <- prcomp(pca_extracts_cdom[,c(1,3,6:8)], scale = TRUE)

# reverse signs of eigenvectors
pc2$rotation <- -1*pc2$rotation

# reverse signs of each observation's principal components scores
pc2$x <- -1*pc2$x

# calculate variance represented by each of the principal components
pc2$sdev^2 / sum(pc2$sdev^2)
```

```{r}
# plot the new PCA
new_pca_plot <- autoplot(pc2, data = cdom_water_extracts, colour = 'transect_location',
                         shape = 'region',
                         frame = T, size = 3, loadings = TRUE,
         loadings.colour = 'black', loadings.size = 3, loadings.label = TRUE,
         loadings.label.colour = 'black',
         loadings.label.hjust = 0.8, loadings.label.vjust = 1.6,
         loadings.label.size = 5.5)

new_pca_plot + scale_fill_manual(values = palette) + 
  scale_color_manual(values= palette) +
  labs(color = "Gradient Location", fill = "Gradient Location", shape = "Region")

#ggsave("cdom_pca.png", path = output_directory, width = 9, height = 5)

```

```{r}
# work more with ggplot and clustering analysis
## customize plots with ggplot
# pull out needed info
pc_df <- data.frame(pc$x, transect_location = cdom_water_extracts$transect_location,
                    region = cdom_water_extracts$region)

# ggplot
ggplot(pc_df, aes(x = PC1, y = PC2, color = transect_location, shape = region)) +
  geom_point(size = 2.5) +
  scale_color_manual(values = palette)

# set up for clustering 
# https://stackoverflow.com/questions/20260434/test-significance-of-clusters-on-a-pca-plot
scores <- pc2$x[,1:3]                        # scores for first three PC's

# k-means clustering
km     <- kmeans(scores, centers=4, nstart=5)
ggdata <- data.frame(scores, Cluster=km$cluster, location=cdom_water_extracts$transect_location,
                     region = cdom_water_extracts$region)

ggplot(ggdata) +
  geom_point(aes(x=PC1, y=PC2, color=factor(location),shape=factor(region)), size=2.5) +
  stat_ellipse(aes(x=PC1,y=PC2,fill=factor(Cluster)),
               geom="polygon", level=0.95, alpha=0.2) +
  guides(color=guide_legend("location"),fill=guide_legend("Cluster"))

```

## Correlations between CDOM Spectral Metrics

```{r, message = FALSE, warning = FALSE}
cdom_corr <- pca_extracts_cdom
cdom_groups <- as.data.frame(cdom_water_extracts[,3])
colnames(cdom_groups) <- "transect_location"

# correlation scatter plot
ggpairs(cdom_corr, ggplot2::aes(color = cdom_groups$transect_location),
        #lower = list(continuous = "smooth"), # adds lm line to the scatterplots
        columnLabels = c("SUVA 254 nm", "Spectral Slope 275-295 nm", "Spectral Slope 350-400 nm",
                         "Slope Ratio", "E2 to E3", "FI", "HIX", "FRESH", "BIX")) +
  ggplot2::scale_fill_manual(values = palette) +
  ggplot2::scale_color_manual(values = palette)
```

## Pulling Specific Metrics

```{r}
# two absorbance metrics
ggplot(cdom_water_extracts, aes(x = SUVA254, y = S350_400, color = transect_location)) +
  geom_point(size = 2.5) +
  scale_color_manual(values = palette) +
  labs(x = "SUVA at 254 nm", y = "Spectral Slope 350-400 nm", color = "Gradient Location")

#ggsave("SUVA254_S350_400.png", path = output_directory, height = 5, width = 7)
```

```{r}
# two fluorescence metrics
ggplot(cdom_water_extracts, aes(x = FI, y = FRESH, color = transect_location)) +
  geom_point(size = 2.5) +
  scale_color_manual(values = palette) +
  labs(x = "Fluorescense Index", y = "Freshness Index", color = "Gradient Location")

#ggsave("FI_FRESH.png", path = output_directory, height = 5, width = 7)
```

### Summary Stats for FRESH, FI, HIX, SUVA254, and S350_400

```{r}
CDOM_sum_mean <- cdom_water_extracts %>%
  select(transect_location, SUVA254, S350_400, FI, FRESH, HIX) %>%
  group_by(transect_location) %>%
  summarize(across(everything(), mean))

colnames(CDOM_sum_mean)[-1] <- paste0(colnames(CDOM_sum_mean)[-1], "_mean")

CDOM_sum_sd <- cdom_water_extracts %>%
  select(transect_location, SUVA254, S350_400, FI, FRESH, HIX) %>%
  group_by(transect_location) %>%
  summarize(across(everything(), sd))

# calculate standard error
CDOM_sum_se <- CDOM_sum_sd
CDOM_sum_se[,c(2:6)] <- CDOM_sum_se[,c(2:6)]/sqrt(10)   # each transect location has 10 samples

colnames(CDOM_sum_se)[-1] <- paste0(colnames(CDOM_sum_se)[-1], "_se")
```

```{r}
# boxplots for indices across the gradient
SUVA <- ggplot(cdom_water_extracts, aes(x = transect_location, y = SUVA254, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "SUVA at 254 nm (L/mg C*m)", color = "") +
  theme(axis.title.x = element_blank(),     
        axis.text.x = element_blank())    # remove the axis labels and ticks for common axis in ggarrange()

SS <- ggplot(cdom_water_extracts, aes(x = transect_location, y = S350_400, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Spectral Slope (350-400 nm)", color = "") +
  theme(axis.title.x = element_blank(),     
        axis.text.x = element_blank())

FI <- ggplot(cdom_water_extracts, aes(x = transect_location, y = FI, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Fluorescence Index", color = "")

FRESH <- ggplot(cdom_water_extracts, aes(x = transect_location, y = FRESH, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Freshness Index", color = "")

HIX <- ggplot(cdom_water_extracts, aes(x = transect_location, y = HIX, color = transect_location)) +
  geom_boxplot(lwd = 1, fatten = 1,
               outlier.shape = NA, show.legend = FALSE) +
  geom_point(position = position_jitterdodge(), size = 2, show.legend = FALSE) +
  scale_color_manual(values = palette) +
  labs(x = "Gradient Location", y = "Humification Index", color = "")

# pull all plots into one figure
ggarrange(SUVA, SS, FI, FRESH, HIX,
          labels ="AUTO", align = "hv")

#ggsave("cdom_indices_boxplots.png", path = output_directory,
       #width = 16, height = 9)
```

```{r}
#checking normality for ANOVA
ggplot(cdom_water_extracts, aes(x = SUVA254, color = transect_location)) +
  geom_density()
ggplot(cdom_water_extracts, aes(x = S350_400, color = transect_location)) +
  geom_density()
ggplot(cdom_water_extracts, aes(x = FRESH, color = transect_location)) +
  geom_density()
ggplot(cdom_water_extracts, aes(x = FI, color = transect_location)) +
  geom_density()
ggplot(cdom_water_extracts, aes(x = HIX, color = transect_location)) +
  geom_density()

# no way to transform well either - tried ln() and log10() transformation with no success
# proceeded with kruskal-wallis test
```

```{r}
# kruskal-wallis tests for difference between transects for the indices
# SUVA254
kruskal.test(SUVA254 ~ transect_location, cdom_water_extracts)
dunn_test(cdom_water_extracts, SUVA254 ~ transect_location, p.adjust.method = "holm")

# S350-400
kruskal.test(S350_400 ~ transect_location, cdom_water_extracts)
dunn_test(cdom_water_extracts, S350_400 ~ transect_location, p.adjust.method = "holm")

# FRESH
kruskal.test(FRESH ~ transect_location, cdom_water_extracts)
dunn_test(cdom_water_extracts, FRESH ~ transect_location, p.adjust.method = "holm")

# FI
kruskal.test(FI ~ transect_location, cdom_water_extracts)
dunn_test(cdom_water_extracts, FI ~ transect_location, p.adjust.method = "holm")

# HIX
kruskal.test(HIX ~ transect_location, cdom_water_extracts)
dunn_test(cdom_water_extracts, HIX ~ transect_location, p.adjust.method = "holm")
```

## Exploring Optical Metrics vs Other Soil Characteristics for CB Sites

```{r}
# edit water body variable 
cdom_water_extracts <- cdom_water_extracts %>%
  mutate(water_body = case_when(
    state == "VA"|state == "MD" ~ "Chesapeake Bay",
    state == "PA"|state == "DE" ~ "Delaware Bay",
    TRUE ~ "Great Lakes"
  ))

# create dataset that is just Chesapeake
cb_cdom_water_extracts <- cdom_water_extracts %>%
  filter(water_body == "Chesapeake Bay")

# general boxplot of SUVA254 distribution
ggplot(cb_cdom_water_extracts, aes(x = transect_location, y = SUVA254, color = transect_location)) +
  geom_boxplot() +
  geom_jitter() +
  labs(x = "Transect Location", y = "SUVA254", color = "")

# pH vs SUVA254
ggplot(cb_cdom_water_extracts, aes(x = ph, y = SUVA254, color = transect_location)) +
  geom_point()

# all extract sites
ggplot(cdom_water_extracts, aes(x = ph, y = SUVA254, color = transect_location)) +
  geom_point()

# specific conductance vs SUVA254
ggplot(filter(cb_cdom_water_extracts, transect_location != "Water"), aes(x = specific_conductance_us_cm, y = SUVA254, color = transect_location)) +
  geom_point()

# salinity vs SUVA254 (for water samples)
ggplot(filter(cb_cdom_water_extracts, transect_location == "Water"), aes(x = sal_psu, y = SUVA254, color = transect_location)) +
  geom_point()

```

